vim.cmd("set termguicolors")

vim.cmd("syntax enable")
vim.cmd("colorscheme OceanicNext")

vim.cmd("highlight! CmpItemAbbrDeprecated guibg=NONE gui=strikethrough guifg=#808080")
vim.cmd("highlight! CmpItemAbbrMatch guibg=NONE guifg=#569CD6")
vim.cmd("highlight! link CmpItemAbbrMatchFuzzy CmpItemAbbrMatch")
vim.cmd("highlight! CmpItemKindVariable guibg=NONE guifg=#9CDCFE")
vim.cmd("highlight! link CmpItemKindInterface CmpItemKindVariable")
vim.cmd("highlight! link CmpItemKindText CmpItemKindVariable")
vim.cmd("highlight! CmpItemKindFunction guibg=NONE guifg=#C586C0")
vim.cmd("highlight! link CmpItemKindMethod CmpItemKindFunction")
vim.cmd("highlight! CmpItemKindKeyword guibg=NONE guifg=#D4D4D4")
vim.cmd("highlight! link CmpItemKindProperty CmpItemKindKeyword")
vim.cmd("highlight! link CmpItemKindUnit CmpItemKindKeyword")

require('packer-config')
require("neodev").setup({})
require('lsp-config.language-server')
require('mason.mason')
require('settings')
require('mappings')
require('colorschemes-config.oceanic')
require('nvim-tree-config')
require('treesitter-config')
require('dap-config')
require('lualine-config')
